version: '3'
services:
  chatserver:
    image: python:3.11.3-alpine3.17 
    restart: unless-stopped
    volumes:
    - ./app/server:/app
    environment: 
    - SERVER_IP=0.0.0.0
    - SERVER_PORT=8889
    working_dir: /app
    ports:
    - 8889:8889
    command:
    - /bin/sh
    - -c
    - 'cd /app && pip3 install -r requirements.txt && python3 server.py'
    networks:
      - progjarnet
  chatclient:
    image: python:3.11.3-alpine3.17 
    restart: unless-stopped
    environment:
      - SERVER_IP=chatserver
      - SERVER_PORT=8889
      - ONWEB=1
    working_dir: /app
    ports:
    - 8550:8550
    volumes:
    - ./app/client:/app
    command:
    - /bin/sh
    - -c
    - 'cd /app && pip3 install -r requirements.txt && python3 chat-flet.py'
    depends_on:
    - chatserver
#    deploy:
#      mode: replicated
#      replicas: 1
    networks:
      - progjarnet
networks:
  progjarnet:
    ipam:
      config:
        - subnet: 172.222.221.0/24
